---
- name: users | creating user accounts
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    shell: "{{ item.shell|default (omit) }}"
    comment: "{{ item.comment|default (omit) }}"
    state: present
  with_items: '{{ create_users }}'
  when: >
        item.setup and
        not item.generate_keys and
        not item.system_account

- name: users | creating user accounts and generating ssh_keys
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    shell: "{{ item.shell|default (omit) }}"
    comment: "{{ item.comment|defaut (omit) }}"
    generate_ssh_key: yes
    state: present
  with_items: '{{ create_users }}'
  when: >
        item.setup and
        item.generate_keys and
        not item.system_account

- name: users | creating system accounts
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    shell: "{{ item.shell|default (omit) }}"
    comment: "{{ item.comment|default (omit) }}"
    system: yes
    state: present
  with_items: '{{ create_users }}'
  when: >
        item.setup and
        not item.generate_keys and
        item.system_account

- name: users | creating system accounts and generating ssh_keys
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    shell: "{{ item.shell|default (omit) }}"
    comment: "{{ item.comment|default (omit) }}"
    generate_ssh_key: yes
    system: yes
    state: present
  with_items: '{{ create_users }}'
  when: >
        item.setup and
        item.generate_keys and
        item.system_account

- name: users | removing user accounts
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    state: absent
  with_items: '{{ create_users }}'
  when: not item.setup

- name: users | adding users to sudoers
  lineinfile:
    dest: "/etc/sudoers"
    regexp: '^{{ item.user }} ALL'
    line: '{{ item.user }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    state: present
  with_items: '{{ create_users }}'
  when: item.sudo

- name: users | removing users from sudoers
  lineinfile:
    dest: "/etc/sudoers"
    regexp: '^{{ item.user }} ALL'
    line: '{{ item.user }} ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    state: absent
  with_items: '{{ create_users }}'
  when: not item.sudo
